"""empty message

Revision ID: 24547d788511
Revises: 13039747aa3
Create Date: 2015-12-07 02:12:50.966826

"""

# revision identifiers, used by Alembic.
revision = '24547d788511'
down_revision = '13039747aa3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('applys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applyer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=200), nullable=True),
    sa.Column('reason', sa.UnicodeText(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('num_comments', sa.Integer(), nullable=True),
    sa.Column('access', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('readed', sa.Integer(), nullable=True),
    sa.Column('result', sa.UnicodeText(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['applyer_id'], [u'users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'users', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column(u'users', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'positions', ['position_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column(u'users', 'position_id')
    op.drop_column(u'users', 'department_id')
    op.drop_table('applys')
    op.drop_table('positions')
    op.drop_table('departments')
    ### end Alembic commands ###
